name: Automatically adds you to the assignees in the pull request
on: [pull_request]
jobs:
  assign_me:
    runs-on: ubuntu-latest
    name: Assign me
    steps:
      - uses: AlbertHernandez/assign-me@v1
    env:
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
